# -*- coding: utf-8 -*-
"""ai_pandas_notebook_2_fixed

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccwXHARXepdk1Myw3WUdmlAclQQFjmSE
"""

#AI Pandas Notebook 2

#Automatically generated by Colab.

#Original file is located at
    #https://colab.research.google.com/drive/1c4uIP2GUWYaIXJ5w_LRWbJuZ1rZ7k5TT

import pandas as pd
titanic = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

from google.colab import drive
drive.mount('/content/drive')

titanic

titanic.head(8)

titanic.dtypes

titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)

titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")

titanic.head()

titanic.info()

ages = titanic["Age"]

ages.head()

type(titanic["Age"])

titanic["Age"].shape

age_sex = titanic[["Age", "Sex"]]

age_sex.head()

type(titanic[["Age", "Sex"]])

titanic[["Age", "Sex"]].shape

above_35 = titanic[titanic["Age"] > 35]

above_35.head()

above_35.shape

class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]

class_23.head()

age_no_na = titanic[titanic["Age"].notna()]

age_no_na.head()

age_no_na.shape

adult_names = titanic.loc[titanic["Age"] > 35, "Name"]

adult_names.head()

titanic.iloc[9:25, 2:5]

titanic.iloc[0:3, 3] = "anonymous"

titanic.head()

import matplotlib.pyplot as plt

air_quality = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_no2.csv", index_col=0, parse_dates=True)

air_quality.head()

air_quality.plot()

plt.show()

air_quality["station_paris"].plot()

plt.show()

air_quality.plot.scatter(x="station_london", y="station_paris", alpha=0.5)

plt.show()

[
    method_name
    for method_name in dir(air_quality.plot)
    if not method_name.startswith("_")
]

air_quality.plot.box()

plt.show()

axs = air_quality.plot.area(figsize=(12, 4), subplots=True)

plt.show()

fig, axs = plt.subplots(figsize=(12, 4))

air_quality.plot.area(ax=axs)

axs.set_ylabel("NO$_2$ concentration")

fig.savefig("no2_concentrations.png")

plt.show()

air_quality.head()

air_quality["london_mg_per_cubic"] = air_quality["station_london"] * 1.882

air_quality.head()

air_quality["ratio_paris_antwerp"] = (
    air_quality["station_paris"] / air_quality["station_antwerp"]
)

air_quality.head()

air_quality_renamed = air_quality.rename(
    columns={
        "station_antwerp": "BETR801",
        "station_paris": "FR04014",
        "station_london": "London Westminster",
    }
)

air_quality_renamed.head()

air_quality_renamed = air_quality_renamed.rename(columns=str.lower)

air_quality_renamed.head()

titanic.head()

titanic["Age"].mean()

titanic[["Age", "Fare"]].median()

titanic[["Age", "Fare"]].describe()

titanic.agg(
    {
        "Age": ["min", "max", "median", "skew"],
        "Fare": ["min", "max", "median", "mean"],
    }
)

titanic[["Sex", "Age"]].groupby("Sex").mean()

titanic.groupby("Sex").mean(numeric_only=True)

titanic.groupby("Sex")["Age"].mean()

titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

titanic["Pclass"].value_counts()

titanic.groupby("Pclass")["Pclass"].count()

titanic.head()

air_quality = pd.read_csv(
    "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_long.csv", index_col="date.utc", parse_dates=True
)

air_quality.head()

titanic.sort_values(by="Age").head()

titanic.sort_values(by=['Pclass', 'Age'], ascending=False).head()

no2 = air_quality[air_quality["parameter"] == "no2"]

no2_subset = no2.sort_index().groupby(["location"]).head(2)

no2_subset

no2_subset.pivot(columns="location", values="value")

no2.head()

no2.pivot(columns="location", values="value").plot()

air_quality.pivot_table(
    values="value", index="location", columns="parameter", aggfunc="mean"
)

air_quality.pivot_table(
    values="value",
    index="location",
    columns="parameter",
    aggfunc="mean",
    margins=True,
)

no2_pivoted = no2.pivot(columns="location", values="value").reset_index()

no2_pivoted.head()

no_2 = no2_pivoted.melt(id_vars="date.utc")

no_2.head()

no_2 = no2_pivoted.melt(
    id_vars="date.utc",
    value_vars=["BETR801", "FR04014", "London Westminster"],
    value_name="NO_2",
    var_name="id_location",
)

no_2.head()

air_quality_no2 = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_no2_long.csv",
                              parse_dates=True)

air_quality_no2 = air_quality_no2[["date.utc", "location",
                                   "parameter", "value"]]

air_quality_no2.head()

air_quality_pm25 = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_pm25_long.csv",
                               parse_dates=True)

air_quality_pm25 = air_quality_pm25[["date.utc", "location",
                                     "parameter", "value"]]

air_quality_pm25.head()

air_quality = pd.concat([air_quality_pm25, air_quality_no2], axis=0)

air_quality.head()

print('Shape of the ``air_quality_pm25`` table: ', air_quality_pm25.shape)

print('Shape of the ``air_quality_no2`` table: ', air_quality_no2.shape)

print('Shape of the resulting ``air_quality`` table: ', air_quality.shape)

air_quality = air_quality.sort_values("date.utc")

air_quality.head()

stations_coord = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_stations.csv")

stations_coord.head()

air_quality.head()

air_quality = pd.merge(air_quality, stations_coord, how="left", on="location")

air_quality.head()

air_quality_parameters = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_parameters.csv")

air_quality_parameters.head()

air_quality = pd.merge(air_quality, air_quality_parameters,
                       how='left', left_on='parameter', right_on='id')

air_quality.head()

air_quality = air_quality.rename(columns={"date.utc": "datetime"})

air_quality.head()

air_quality["datetime"] = pd.to_datetime(air_quality["datetime"])

air_quality["datetime"]

air_quality["datetime"].min(), air_quality["datetime"].max()

air_quality["datetime"].max() - air_quality["datetime"].min()

air_quality["month"] = air_quality["datetime"].dt.month

air_quality.head()

air_quality.groupby(
    [air_quality["datetime"].dt.weekday, "location"])["value"].mean()

fig, axs = plt.subplots(figsize=(12, 4))

air_quality.groupby(air_quality["datetime"].dt.hour)["value"].mean().plot(
    kind='bar', rot=0, ax=axs
)

plt.xlabel("Hour of the day");  # custom x label using Matplotlib

plt.ylabel("$NO_2 (µg/m^3)$");

no_2 = air_quality.groupby(["datetime", "location"])["value"].mean().reset_index()
no_2 = no_2.pivot(index="datetime", columns="location", values="value")
no_2.head()

air_quality = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/air_quality_no2_long.csv")

air_quality = air_quality.rename(columns={"date.utc": "datetime"})

air_quality.head()

air_quality["datetime"] = pd.to_datetime(air_quality["datetime"])

air_quality["datetime"]

air_quality["datetime"].min(), air_quality["datetime"].max()

air_quality["datetime"].max() - air_quality["datetime"].min()

air_quality["month"] = air_quality["datetime"].dt.month

air_quality.head()

air_quality.groupby(
    [air_quality["datetime"].dt.weekday, "location"])["value"].mean()

fig, axs = plt.subplots(figsize=(12, 4))

air_quality.groupby(air_quality["datetime"].dt.hour)["value"].mean().plot(
    kind='bar', rot=0, ax=axs
)

plt.xlabel("Hour of the day");  # custom x label using Matplotlib

plt.ylabel("$NO_2 (µg/m^3)$");

no_2 = air_quality.pivot(index="datetime", columns="location", values="value")

no_2.head()

no_2.index.year, no_2.index.weekday

no_2["2019-05-20":"2019-05-21"].plot();

monthly_max = no_2.resample("ME").max()

monthly_max

monthly_max.index.freq

no_2.resample("D").mean().plot(style="-o", figsize=(10, 5));

titanic.head()

titanic["Name"].str.lower()

titanic["Name"].str.split(",")

titanic["Surname"] = titanic["Name"].str.split(",").str.get(0)

titanic["Surname"]

titanic["Name"].str.contains("Countess")

titanic[titanic["Name"].str.contains("Countess")]

titanic["Name"].str.len()

titanic["Name"].str.len().idxmax()

titanic.loc[titanic["Name"].str.len().idxmax(), "Name"]

titanic["Sex_short"] = titanic["Sex"].replace({"male": "M", "female": "F"})

titanic["Sex_short"]